---
- name: CFME | Update OS | Any package updates required?
  command: 'yum check-update'
  args:
    warn: no
  register: packages_need_update_result
  changed_when: packages_need_update_result.rc == 100
  failed_when: packages_need_update_result.rc != 0 and packages_need_update_result.rc != 100

- block:
    - name: CFME | Update OS | Update Packages
      package:
        name: '*'
        state: latest
    
    - name: CFME | Update OS | Include Tasks for Host Reboot
      include_tasks: tasks/reboot.yml
