- name: CFME | Change VMDB Password | Appliances Specific Preparation
  hosts: cfme-appliances
  become: True
  become_method: su
  gather_facts: False
  vars_files:
    - files/vmdb_password.yml
  tasks:
    - name: CFME | Change VMDB Password | Stop evmserverd
      service:
        name: evmserverd
        state: stopped
    - name: CFME | Change VMDB Password | Update database.yml file.
      shell: "/var/www/miq/vmdb/tools/fix_auth.rb --databaseyml --password '{{ vmdb_password }}'"

- name: CFME | Change VMDB Password | Change PostgreSQL Password
  hosts: "{{ groups['cfme-databases'][0] }}"
  become: True
  gather_facts: False
  vars_files:
    - files/vmdb_password.yml
  tasks:
    - name: CFME | Change VMDB Password | Install python-psycopg2
      yum:
        name: python-psycopg2
        state: latest
    - name: CFME | Change VMDB Password | Change PostgreSQL Password
      postgresql_user:
        db: vmdb_production
        name: root
        password: "{{ vmdb_password }}"

- name: CFME | Change VMDB Password | Restart evmserverd
  hosts: cfme-appliances
  become: True
  gather_facts: False
  tasks:
    - name: CFME | Change VMDB Password | Restart evmserverd
      service:
        name: evmserverd
        state: restarted
