- name: CFME | Migrate | 5.8 to 5.9 | All Preparation
  hosts: cfme
  become: True
  gather_facts: True
  tasks:
    - name: CFME | Migrate | Subscribe Using Activation Key
      include_tasks: tasks/configure-activation-key.yml
      when: sat6_activation_key is defined

    - name: CFME | Migrate | Subscribe Using Repositories
      include_tasks: tasks/configure-repositories.yml
      vars:
        cfme_version_product: 5.9
      when: sat6_activation_key is not defined

- name: CFME | Migrate | 5.8 to 5.9 | Appliances Specific Preparation
  hosts: cfme-appliances
  become: True
  gather_facts: False
  tasks:
    - name: CFME | Migrate | Stop evmserverd
      service:
        name: evmserverd
        state: stopped

- name: CFME | Migrate | 5.8 to 5.9 | DB Specific Preparation
  hosts: cfme-databases
  become: True
  gather_facts: False
  tasks:
    - name: CFME | Migrate | Stop postgres
      service:
        name: rh-postgresql95-postgresql
        state: stopped

- name: CFME | Migrate | 5.8 to 5.9 | Update Packages
  hosts: cfme
  become: True
  gather_facts: False
  tasks:
    - name: CFME | Migrate | Update all packages to latest
      yum:
        name: '*'
        state: latest

- name: CFME | Migrate | 5.8 to 5.9 | Start postgresql
  hosts: cfme-databases
  become: True
  gather_facts: False
  tasks:
    - name: CFME | Migrate | Start postgres
      service:
        name: rh-postgresql95-postgresql
        state: started

- name: CFME | Migrate | 5.8 to 5.9 | DB Migration
  hosts: cfme-appliances
  become: True
  gather_facts: False
  tasks:
    - name: CFME | Migrate | rake db:migrate
      run_once: True
      shell: "cd /var/www/miq/vmdb; rake db:migrate | tee /var/tmp/rake_db_migrate.out"
      async: 18000
      poll: 60

    - name: CFME | Migrate | rake evm:automate:reset
      run_once: True
      shell: "cd /var/www/miq/vmdb; rake evm:automate:reset | tee /var/tmp/evm_automate_reset.out"
      async: 3600
      poll: 60

- name: CFME | Migrate | 5.8 to 5.9 | Post DB Migrate Restart
  hosts: cfme-databases
  become: True
  gather_facts: False
  tasks:
    - name: CFME | Migrate | Restart postgresql
      service:
        name: rh-postgresql95-postgresql
        state: restarted

- name: CFME | Migrate | 5.8 to 5.9 | Restart evmserverd
  hosts: cfme-appliances
  become: True
  gather_facts: False
  tasks:
    - name: CFME | Migrate | Restart evmserverd
      service:
        name: evmserverd
        state: restarted
