- name: CFME | Migrate | 5.7 to 5.8 | All Preparation
  hosts: cfme
  become: True
  gather_facts: True
  tasks:
    - name: CFME | Migrate | Subscribe Using Activation Key
      include_tasks: tasks/configure-activation-key.yml
      when: sat6_activation_key is defined

    - name: CFME | Migrate | Subscribe Using Repositories
      include_tasks: tasks/configure-repositories.yml
      vars:
        cfme_version_product: 5.8
      when: sat6_activation_key is not defined

- name: CFME | Migrate | 5.7 to 5.8 | Appliances Specific Preparation
  hosts: cfme-appliances
  become: True
  gather_facts: False
  tasks:
    - name: CFME | Migrate | Stop evmserverd
      service:
        name: evmserverd
        state: stopped

- name: CFME | Migrate | 5.7 to 5.8 | DB Specific Preparation
  hosts: cfme-databases
  become: True
  gather_facts: False
  tasks:
    - name: CFME | Migrate | Stop postgres
      service:
        name: rh-postgresql95-postgresql
        state: stopped

- name: CFME | Migrate | 5.7 to 5.8 | Update Packages
  hosts: cfme
  become: True
  gather_facts: False
  tasks:
    - name: CFME | Migrate | Update all packages to latest
      yum:
        name: '*'
        state: latest

- name: CFME | Migrate | 5.7 to 5.8 | Start postgresql
  hosts: cfme-databases
  become: True
  gather_facts: False
  tasks:
    - name: CFME | Migrate | Start postgres
      service:
        name: rh-postgresql95-postgresql
        state: started

- name: CFME | Migrate | 5.7 to 5.8 | DB Migration
  hosts: cfme-appliances
  become: True
  gather_facts: False
  tasks:
    - name: CFME | Migrate | rake db:migrate
      run_once: True
      shell: "cd /var/www/miq/vmdb; rake db:migrate | tee /var/tmp/rake_db_migrate.out"
      async: 18000
      poll: 60

    - name: CFME | Migrate | rake evm:automate:reset
      run_once: True
      shell: "cd /var/www/miq/vmdb; rake evm:automate:reset | tee /var/tmp/evm_automate_reset.out"
      async: 3600
      poll: 60

- name: CFME | Migrate | 5.7 to 5.8 | Post DB Migrate Restart
  hosts: cfme-databases
  become: True
  gather_facts: False
  tasks:
    - name: CFME | Migrate | Restart postgresql
      service:
        name: rh-postgresql95-postgresql
        state: restarted

- name: CFME | Migrate | 5.7 to 5.8 | Check Schema
  hosts: cfme-appliances
  become: True
  gather_facts: False
  tasks:
    - name: CFME | Migrate | Check DB Schema
      block:
        - name: CFME | Migrate | rake evm:db:check_schema
          shell: "cd /var/www/miq/vmdb; rake evm:db:check_schema | tee /var/tmp/evm_check_schema.out"
          register: evm_db_check_schema_cmd
          changed_when: False
          async: 3600
          poll: 60
    
        # Using assert module due to bug in async/poll. https://github.com/ansible/ansible/issues/32472
        - name: CFME | Migrate | Assert evm:db:check_schema result
          assert:
            that: "evm_db_check_schema_cmd.rc == 0 and 'The local schema is consistent with schema.yml' in evm_db_check_schema_cmd.stdout"
      run_once: True
      tags:
        - evm_check_schema

- name: CFME | Migrate | 5.7 to 5.8 | Restart evmserverd
  hosts: cfme-appliances
  become: True
  gather_facts: False
  tasks:
    - name: CFME | Migrate | Restart evmserverd
      service:
        name: evmserverd
        state: restarted
